services:
    Doctrine\DBAL\Connection:
        class: Doctrine\DBAL\Connection
        factory: [Doctrine\DBAL\DriverManager, getConnection]
        arguments:
            -
                driver: pdo_pgsql
                user: '%env(string:APP_PDO_USER)%'
                password: '%env(string:APP_PDO_PWD)%'
                url: '%env(string:APP_PDO_DSN)%'
