services:
    Doctrine\DBAL\Connection:
        class: Doctrine\DBAL\Connection
        factory: [Doctrine\DBAL\DriverManager, getConnection]
        arguments:
            -
                driver: pdo_pgsql
                host: '%env(string:APP_PDO_HOST)%'
                port: '%env(string:APP_PDO_PORT)%'
                dbname: '%env(string:APP_PDO_DB)%'
                user: '%env(string:APP_PDO_USER)%'
                password: '%env(string:APP_PDO_PWD)%'
