version: '2'

services:
    php:
        build: ./docker/php
        volumes:
            - .:/app
        working_dir: /app
        ports:
            - 8080:8080
        entrypoint: php
        command: bin/console server:run 0.0.0.0:8080

    postgres:
        image: postgres:alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=gildasquemener
            - POSTGRES_PASSWORD=gildasquemener
        volumes:
            - ./docker/pgsql:/docker-entrypoint-initdb.d
            - ./db:/var/lib/postgresql/data
