monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: stdout
        stdout:
            type: stream
            path: "php://stdout"
            formatter: 'monolog.formatter.json'
