monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: stdout
            excluded_http_codes: [404, 405]
        stdout:
            type: stream
            path: "php://stdout"
