app_contribution_index:
    path: /api/contributions
    controller: App\Controller\ContributionController::index

homepage:
    path: /{_}
    controller: App\Controller\DefaultController::index
    defaults:
        _: null
    requirements:
        _: '.*'
