# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    # App\Controller\:
    #     resource: '../src/Controller'
    #     tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.command_handler_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments:
            -
                App\Github\Domain\Command\SynchronizePullRequests: '@App\Github\Domain\Command\SynchronizePullRequestsHandler'

    App\ServiceBus\CommandBus:
        class: App\ServiceBus\ServiceLocatorCommandBus
        arguments:
            - '@app.command_handler_locator'

    App\ServiceBus\EventBus:
        class: App\ServiceBus\SymfonyDispatcherEventBus
        arguments:
            - '@app.domain_event_dispatcher'

    app.domain_event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher
        calls:
            - ['addListener', ['App\Github\Domain\Event\PullRequestFound', '@App\Contribution\Domain\Listener\SynchronizeContribution']]
            - ['addListener', ['App\Github\Domain\Event\MergedPullRequestFound', '@App\Contribution\Domain\Listener\MarkMergedContribution']]
